-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        dim_inactive = true,
        rounding = 20,
    },
    general = {
        gaps_in = 4,
        gaps_out = 50,
        layout = "scrolling",
    },
    misc = {
        vrr = 0,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
