# --- Font ---
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# --- Smooth Cursor Trail ---
cursor_style                  block
cursor_blink_interval        0.5
cursor_trail                 1
cursor_trail_decay           0.1 0.4
cursor_trail_start_threshold 2

# --- Window Styling ---
window_padding_width 10
confirm_os_window_close 0

include theme.conf
